### ISSUE TITLE
Policies für Rollen konfigurieren

### ISSUE THREAD

**Issue by danjov** [GeoWerkstatt/ews-boda#10]
* Wer darf was?
* API Absicherung

**Comment by flenny** [comment]
**markus.staehli (Guest) am Fr. 8. Juli 2022 08:21 Uhr im Teams**
> Externe Büros dürfen Standorte löschen, solange sie noch nicht durch das AfU freigegeben wurden. Freigegebene Standorte hingegen dürfen sie nicht mehr löschen.
