### ISSUE TITLE
Kartendarstellung geht verloren

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#111]
**Repro-Steps**
1. Öffne Formular _Standortsuche_
2. Öffne Formular _Benutzerverwaltung_
3. Kehre zurück zu Formular _Standortsuche_

**Festgestelltes Verhalten**
Im Kartenfenster fehlt die Kartendarstellung. Diese erscheint auch nach einer Suche nicht mehr.

**Erwartetes Verhalten**
Das Kartenfenster zeigt die Kartendarstellung

**Comment by StefanKiener** [comment]
Das Verhalten hat sich nicht geändert, der Fehler existiert weiterhin

**Comment by MiraGeowerkstatt** [comment]
Das Problem tritt soweit ich sehe nicht im Chrome Browser auf und nur manchmal im Edge Browser. Während der lokalen Entwicklung tritt es auch im Chrome nie auf.

**Comment by StefanKiener** [comment]
Für das AfU sind die Browser Edge und Firefox massgebend (Chrome wird nicht verwendet). Im Edge tritt das Problem bei mir regelmässig auf, Firefox habe ich noch nicht getestet.

**Comment by danjov** [comment]
@StefanKiener Tritt das Problem weiterhin auf? Wenn ja, gleich wenn du dich angemeldet hast oder erst später? Ich konnte den Fehler mit Microsoft Edge und mit Mozilla Firefox nicht reproduzieren.

**Comment by StefanKiener** [comment]
@danjov Problem ist auch bei mir nicht mehr reproduzierbar. Ich schliesse das Issue.

**Comment by StefanKiener** [comment]
@danjov Das Problem tritt doch auf und lässt sich mit den Repro-Steps reproduzieren

**Comment by StefanKiener** [comment]
Konsolenmeldung in Edge: 
No map visible because the map container's width or height are 0.

**Comment by MiraGeowerkstatt** [comment]
Ich kann das Problem auch reproduzieren. Dem map canvas wird "display:none" hinzugefügt. Sobald das die Fenstergrösse ändert erscheint die Karte wieder. Etwas ähnliches ist hier beschrieben, obwohl das schon eine viel ältere openlayers Version ist.

https://github.com/openlayers/openlayers/issues/4601
