### ISSUE TITLE
Formular Standort: Bemerkungsfeld mehrzeilig und mit Möglichkeit für Zeilenumbruch definieren

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#116]
Das Control 'Bemerkungen zum Standort' sollte (gemäss Mockup) mehrzeilig sein und es sollte die Möglichkeit bieten, einen Zeilenumbruch einzufügen.

**Comment by MiraGeowerkstatt** [comment]
Ich habe die Bemerkungsfelder so angepasst, dass sie Zeilenumbrüche akzeptieren und sich die Grösse bei Bedarf anpasst. 
So nehmen sie nicht immer so viel Platz ein, auch wenn nur eine einzelige Bemerkung oder nichts drin steht.



![Image](https://user-images.githubusercontent.com/49144408/181274108-93ae0aa6-cb84-4dce-aa53-fde6e055ef74.png)



![Image](https://user-images.githubusercontent.com/49144408/181274015-8442690a-e14d-42f2-bd8b-3ab803b1e4b7.png)
