### ISSUE TITLE
Einstiegsseite mit Suche

### ISSUE THREAD

**Issue by danjov** [GeoWerkstatt/ews-boda#13]
- [x] Suchresultate in Karte anzeigen
- [x] Suchresultate in Grid anzeigen

Es soll geprüft werden, ob die Suche mit nur einem Suchfeld für alle Daten realisiert werden kann.

Mockup:
![image](https://user-images.githubusercontent.com/8969524/169059117-885fe151-c875-42ea-add9-a6859df04c42.png)

**Comment by StefanKiener** [comment]
Markus Stähli zum Löschen von Standorten:
Externe Büros dürfen Standorte löschen, solange sie noch nicht durch das AfU freigegeben wurden. Freigegebene Standorte hingegen dürfen sie nicht mehr löschen.

**Comment by MarkusStaehli** [comment]
Jetzt funktioniert die Suche nach Erstellungs- und Mutationsdatum korrekt.
