### ISSUE TITLE
OpenLayers Kartenkomponente

### ISSUE THREAD

**Issue by danjov** [GeoWerkstatt/ews-boda#15]
- [x] Hintergrundkarte schwarz/weiss als WMTS: https://so.ch/verwaltung/bau-und-justizdepartement/amt-fuer-geoinformation/geoportal/geodienste/wmts-web-map-tile-service/
- [x] Fachdaten über API als GeoJSON (inkl. Symbolisierung)
- [x] Kartenwerkzeuge: Zoom In, Zoom Out, Pan, Ansicht zuück (_letzten Extent anzeigen_), Ansicht gesamter Kanton, Info-Button (siehe auch Mockup). Info-Button kann womöglich auch weggelassen werden

![image](https://user-images.githubusercontent.com/8969524/169062099-bbd04d85-336b-41c0-91f3-01189189466f.png)

**Comment by StefanKiener** [comment]
Nachricht Markus Stähli zum Inhalt des Info-Fensters: 
Folgende Angaben sollten dargestellt werden: Bezeichnung / Gemeinde / bgnummer / datum

**Comment by MarkusStaehli** [comment]
Kartenfenster und Navigation ist i.o.
