### ISSUE TITLE
Alle Formulare: Einheitliche Verwendung von Speichern, Abbrechen, Schliessen

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#150]
Alle Formulare sollen dasselbe Verhalten wie das Formular _Standort_ verwenden:
- Zu Beginn zeigt das Formular die Funktionen _Abbrechen_ und _Speichern_
- Nach dem Speichern zeigt das Formular die Funktionen _Schliessen_ und _Speichern_ (disabled)
- Nach einem erneuten Editieren zeigt das Formular die Funktionen _Abbrechen_ und _Speichern_
- Das Formular wird (beim Speichern) nie automatisch geschlossen, sondern immer explizit über die Funktion _Schliessen_

**Comment by danjov** [comment]
@StefanKiener Korrektur: Zu Beginn sollte das Formular das selbe anzeigen, wie nach dem Speichern. Also wäre es wie folgt:
- Zu Beginn und nach dem Speichern zeigt das Formular die Funktionen _Schliessen_ und _Speichern_ (disabled)
- Nach einem Editieren zeigt das Formular die Funktionen _Abbrechen_ und _Speichern_
- Das Formular wird (beim Speichern) nie automatisch geschlossen, sondern immer explizit über die Funktion _Schliessen_

**Comment by StefanKiener** [comment]
@danjov Dein Einwand ist korrekt. Es muss aber noch für alle Formulare entsprechend umgesetzt werden, z.B. das Formular _Bohrung_ zeigt beim Öffnen die Funktion _Abbrechen_ anstatt _Schliessen_.

**Comment by danjov** [comment]
Das Verhalten im Formular _Bohrung_ tritt auf, da das Formular von Anfang als geändert (`isDirty == true`) angesehen wird.

**Comment by StefanKiener** [comment]
@danjov Ist dieses Verhalten (isDirty == true) von Beginn weg denn gewollt oder handelt es sich um einen Fehler?

**Comment by danjov** [comment]
@StefanKiener Das ist ein Fehler. Mein Kommentar soll nur ein Hinweis sein für den Entwickler, der den Fehler behebt.
