### ISSUE TITLE
Einstiegsseite: Suche zurücksetzen führt sporadisch zu leerer Seite

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#168]
Die Funktion _Suche zurücksetzen_ führt bei meinen Tests mit dem Edge-Browser sporadisch zu einer vollkommen leeren Seite. Durch die Browser-Funktion _Aktualisieren_ wird die Seite zwar wieder aufgebaut, das Kartenfenster bleibt aber permanent leer (auch nach einer erneuten Suche). Eindeutige Repro-Steps für das Problem kann ich leider nicht liefern.

**Comment by danjov** [comment]
Das Problem konnte mit Microsoft Edge und Mozilla Firefox nicht reproduziert werden. @StefanKiener Tritt der Fehler bei dir noch sporadisch auf?

**Comment by StefanKiener** [comment]
@danjov Das Problem kann nicht mehr reproduziert werden. Ich schliesse das Issue.
