### ISSUE TITLE
Formular Standort: Fehlverhalten bei Schliessen

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#173]
**Repro-Steps**
1. Suche Standort in Gemeinde "Buchegg"
2. Navigiere in Standortliste zu Seite 2
3. Öffne Formular Standort bearbeiten
4. Editiere einen Wert
5. Speichere den Standort
6. Schliesse das Formular

**Erwartetes Verhalten**
Die Standortliste steht nach wie vor bei Seite 2 (auf der Seite mit dem bearbeiteten Standort).

**Beobachtetes Verhalten**
Die Standortliste steht bei Seite 1

**Comment by StefanKiener** [comment]
Das Verhalten ist unverändert falsch

**Comment by MiraGeowerkstatt** [comment]
Ich kann das Verhalten nicht reprodzieren.

**Comment by StefanKiener** [comment]
@MiraGeowerkstatt  Scheint sich erledigt zu haben
