### ISSUE TITLE
Formular Bohrung: Darstellungsfehler bei Navigation (vor/zurück)

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#180]
Hat man einen Standort mit mehreren Bohrungen und navigiert mit den Funktionen _Zur nächsten Bohrung_ / _Zur vorherigen Bohrung_ durch die Bohrungen, werden die Informationen in Controls teilweise durch die Labels der Controls überlagert

![Image](https://user-images.githubusercontent.com/11230325/181728305-22208b8c-f43e-404d-b5df-a7f1b5d59b1c.png)

**Comment by MiraGeowerkstatt** [comment]
Anmerkung: Das Problem tritt immer dann auf, wenn im ersten angezeigten Formular das Feld leer ist.
