### ISSUE TITLE
Funktion "Neuen Standort erstellen" führt zu Fehler

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#211]
Die Funktion Neuen Standort erstellen generiert eine leere Seite

**Comment by danjov** [comment]
@StefanKiener Der Fehler kann mit Microsoft Edge und Mozilla Firefox nicht reproduziert werden. Tritt der Fehler bei dir (noch) auf?

**Comment by StefanKiener** [comment]
@danjov Der Fehler scheint behoben zu sein, ich schliesse das Issue
