### ISSUE TITLE
Formular Standort: Verhalten für Control "Freigabe AfU" anpassen

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#218]
Die Controls _AfU Freigabe erfolgt durch_ und _AfU Freigabe erfolgt am_ sollen immer sichtbar sein (unabhängig vom Status der CheckBox _Freigabe AfU_).
Die Controls sollen bei einer Änderung der CheckBox _Freigabe AfU_ unmittelbar nachgeführt werden (ausgefüllt werden oder geleert werden).

**Comment by danjov** [comment]
Der erste Teil des Issues wurde mit #229 erledigt. Offen bleibt die unmittelbare Nachführung der _Freigabe AfU_-Werte.
