### ISSUE TITLE
Rolle Extern: Verschiebung Bohrstandort in Karte deaktivieren

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#219]
**Repro-Steps**
1. In Applikation anmelden mit Rolle _Extern_
2. Formular _Standort bearbeiten_ öffnen (Freigabe Afu = True)
3. Formular _Bohrung bearbeiten_ öffnen
4. Bohrungsstandort duch Klicken in der Karte verändern

**Erwartetes Verhalten**
Der Bohrungsstandort lässt sich für den Benutzer mit der Rolle _Extern_ nicht verändern.

**Beobachtetes Verhalten**
Der Bohrungsstandort kann durch den Benutzer mit der Rolle _Extern_ verändert werden.

**Comment by danjov** [comment]
@StefanKiener Gilt das immer oder nur wenn der Standort bereits freigegeben wurde?

**Comment by StefanKiener** [comment]
@danjov Gilt nur wenn der Standort vom AfU freigegeben wurde
