### ISSUE TITLE
Formular Bohrung: Speichern nicht möglich

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#222]
**Repro-Steps**
1. Funktion _Neuen Standort erstellen_ aufrufen
2. _Bezeichnung_ des Standort definieren
3. _Standort speichern_
4. Formular schliessen
5. Erstellten Standort suchen
6. Formular _Standort bearbeiten_ öffnen
7. Funktion _Bohrung hinzufügen_ aufrufen
8. Angaben in Formular Bohrung ausfüllen
9. Bohrung speichern

**Erwartetes Verhalten**
Bohrung wird gespeichert und Formular kann geschlossen werden.

**Beobachtetes Verhalten**
Es erfolgt keine Speicherung.

**Comment by StefanKiener** [comment]
Kein verändertes Verhalten feststellbar.

**Comment by danjov** [comment]
@StefanKiener Der Bugfix ist erst in Version [https://github.com/GeoWerkstatt/ews-boda/releases/tag/v0.1.102](https://github.com/GeoWerkstatt/ews-boda/releases/tag/vc) enthalten.
