### ISSUE TITLE
Datenimport: Fehler bei Umlauten

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#241]
Bei neu in die Datenbank importierten Daten zeigen sich Fehler bei den Umlauten. Die Abbildung zeigt das Beispiel der neu hinzugefügten Codewerte für Vorkommnisse.
Das Problem ist vermutlich bei allen Datenimporten (nicht nur bei den Codewerten Vorkommnisse) vorhanden.

![Image](https://user-images.githubusercontent.com/11230325/182766311-8f5de9f3-8044-4fdd-be76-5e89002dc503.png)

**Comment by danjov** [comment]
Fehler ist bekannt und wird bei der nächsten Migration nicht mehr auftreten. Die Umlaute gingen beim Transferieren der Migrationsskripts zum Zielsystem beim Kunden verloren und deshalb fehlen sie bei den neuen Codewerten.
