### ISSUE TITLE
Formular Standort: Fehlerhafte Darstellung bei Statusänderung "Freigabe AfU"

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#250]
**Repro-Steps**
1. Öffne Formular Standort für einen Standort mit _Freigabe AfU_ = False
2. Setze  _Freigabe AfU_ = True
3. Speichere den Standort
4. Setze  _Freigabe AfU_ = False
5. Speichere den Standort

**Erwartetes Verhalten**
Die Werte in den Controls _AfU Freigabe erfolgt durch_ und _AfU Freigabe erfolgt am_ werden gelöscht und die Controls nehmen den "leeren Zustand" an.

Beobachtetes Verhalten
Die Controls nehmenden "leeren Zustand" an, aber die Werte in den Controls werden nicht gelöscht.

![Image](https://user-images.githubusercontent.com/11230325/182838020-c34da45a-d242-45a8-82ea-a4d792b04921.png)

**Comment by danjov** [comment]
@StefanKiener Der Fehler kann mit der aktuellen Version nicht mehr reproduziert werden.
