### ISSUE TITLE
Formular Bohrprofil: Anordnung Controls ändern

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#259]
Das Control _Formation Endtiefe_ rechts neben dem Control _Formation Felsoberfläche_ positionieren.

**Comment by MiraGeowerkstatt** [comment]
In dem Fix habe ich auch die Dropdowns für "Klassierung der Tektonik" und "Qualität der Angaben zum Bohrprofil" schmaler und neben einander positioniert damit das Formular einheitlich aussieht.

**Comment by StefanKiener** [comment]
@MiraGeowerkstatt Die zwei Felder  _Formation Felsoberfläche_ und _Formation Endtiefe_ sollten entweder direkt untereinander oder nebeneinander platziert werden (nicht über Kreuz).
