### ISSUE TITLE
Formular Bohrprofil: Inhalt und Sortierung für Felder "Formation Felsoberfläche" und "Formation auf Endtiefe" anpassen

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#269]
Für die Controls _Formation Felsoberfläche_ und _Formation auf Endtiefe_ soll das Feld [code].[kurztext] verwendet werden. Die Einträge im Control sollen aufsteigend sortiert sein nach dem Feld [code].[code_id]

Sortiert nach dem Feld «code_id», aufsteigend von 2 bis 113 (zuoberst Quartär, zuunterst  Kristallin_Gneis).

**Comment by StefanKiener** [comment]
@MiraGeowerkstatt Da ich keinen Zugang zur Datenbank habe, kann ich nicht sicher beurteilen, ob die Sortierung wirklich nach dem Feld [code].[code_id] erfolgt. Es gibt aber einen Wert, der mich an der korrekten Sortierung zweifeln lässt.  Der zweitletzte Wert lautet aktuell "Tertiär_Molasse", dieser Wert müsste eigentlich viel weiter oben in der Liste erscheinen, bei den anderen Werten "Tertiär_xxx". Ist die Sortierung falsch, oder hat der Eintrag "Tertiär_Molasse" in der DB einen falschen Wert?

**Comment by MiraGeowerkstatt** [comment]
Ich habe ebenfalls keinen Zugriff auf die Datenbank. Bin mir aber ziemlich sicher, dass es nach der code_id sortiert wird. Ich würde sagen das überlassen wir dem Kunden zum Testen. Sie können beurteilen, ob da alles richtig ist und ob die Codes richtig vergeben wurden.

**Comment by MarkusStaehli** [comment]
Es wird aktuell nach code_id sortiert. Die DB ist hier aber tatsächlich nicht ganz sauber. Der Wert "Tertiär_Molasse" wurde offenbar nachträglich eingefügt. Sorry, das habe ich vorhin nicht bemerkt.

Die Tabelle "code" enthält jedoch noch ein Feld "sort" (Tabelle siehe Anhang). Wenn man danach sortiert, müsste die Reihenfolge überall stimmen. Kann man das noch ändern?

**Comment by MarkusStaehli** [comment]
[Tabelle_code.xlsx](https://github.com/GeoWerkstatt/ews-boda/files/9308935/Tabelle_code.xlsx)
