### ISSUE TITLE
Einstiegsseite: Link aus Info-Popup zu Standort-Formular

### ISSUE THREAD

**Issue by StefanKiener** [GeoWerkstatt/ews-boda#270]
Das Info-Popup im Kartenfenster soll ergänzt werden mit einem Link _Standort editieren_. Der Link öffnet das Formular Standort für die im Kartenfenster selektierte Bohrung.
Falls der aktuelle Benutzer kein Recht hat, den Standort zu editieren, soll der Link-Text _Standort anzeigen_ anstatt _Standort editieren_ heissen.

**Comment by StefanKiener** [comment]
Die Eigenschaften _Standort editieren_ und _Standort anzeigen_ werden noch nicht richtig gesetzt.

**Comment by MarkusStaehli** [comment]
Das tönt zwar merkwürdig, mittlerweile bin ich jedoch sicher:
Wenn ich über das Info-Popup zum Standort und dann weiter zu Bohrung gehe, werden mir die Bohrprofile nicht angezeigt.

Das tritt nicht auf, wenn ich über die Suchresultate unten auf der Startseite einsteige.
