### ISSUE TITLE
Betriebshandbuch

### ISSUE THREAD

**Issue by danjov** [GeoWerkstatt/ews-boda#28]
- [ ] Betriebshandbuch / Betriebsprozesse definieren
- [ ] Benutzerhandbuch abrunden

**Comment by StefanKiener** [comment]
Das AIO wurde für eine Vorlage eines Betriebshandbuchs angefragt.
Intern bei der GeoWerkstatt existieren Beispiele für die Anwendungen _ÖREB-Kataster_ und _BZStat Online_ im Verzeichnis K:\Hilfsmittel\Betriebshandbuch_Vorlage

**Comment by StefanKiener** [comment]
Das Betriebshandbuch wurde durch uns soweit möglich erstellt und am 11. Oktober dem AfU und AIO zur Vervollständigung übergeben.
