### ISSUE TITLE
Datenmigration

### ISSUE THREAD

**Issue by danjov** [GeoWerkstatt/ews-boda#6]

**Comment by StefanKiener** [comment]
Betreffend Migration der Standort-Koordinaten:
- Das Feld wkb_geometry enthält für alle (!) Bohrungen LV 95 Koordinaten. Die alten LV 03 Koordinaten existieren nicht mehr und das Feld wkb_geometry95 ist überflüssig.
- Bei der Migration können die Koordinaten aus dem bisherigen Feld wkb_geometry in die neue Datenstruktur migriert werden.
- Alle Koordinaten sollen auf 1 Nachkommastelle gerundet werden

**Comment by StefanKiener** [comment]
Folgende fehlerhaften Koordinaten wurden dem Auftraggeber gemeldet:
Koordinaten mit zu grossen X-Werten: EWS 235.086.040, EWS 235.090.083, EWS 235.091.043
Koordinaten mit zu kleinen Y-Werten: EWS 235.004.139

**Comment by StefanKiener** [comment]
Anleitung Datenimport von Markus Stähli (E-Mail vom 2.5.2022:

> Ich bin heute die vorhandenen Daten nochmals durchgegangen. Dabei habe ich mich nochmals überzeugt, dass mit dem angepassten Schema keine Daten, welche wir noch benötigen, verloren gehen. Daher verzichte ich darauf, ein separates Dokument «Importanleitung» zu erstellen, gebe euch jedoch gerne folgende Bemerkungen für den Import mit:
> 
> -	Bei sämtlichen Feldern, die nicht mehr benötigt werden und die im angepassten Schema (s. Anhang) rot durchgestrichen sind, können die Daten gelöscht werden.
> 
> -	Bei sämtlichen Feldern, die bestehen bleiben, können die vorhandenen Daten 1:1 übernommen werden.
> -	Neues Feld «gemeinde» in der Tabelle «standort»: Ist es möglich, die Gemeinden für die alten Daten ebenfalls gleich über den Data Service API beim AGI einzutragen? (Allenfalls erst beim definitiven Import und noch nicht für die Testdaten).
> (Oder wird dieser Wert in der Anwendung gar nicht gespeichert, sondern immer bei Bedarf abgerufen?)
> -	Beim Feld «gbnummer» überlasse ich es euch, ob ihr die bestehenden Daten importieren oder ebenfalls über den Data Service einfüllen möchtet.
> -	Die Felder «new_date», «mut_date», «new_usr» und «mut_usr» werden zwar in der neuen Anwendung automatisch ausgefüllt. Die vorhandenen Einträge in den bestehenden Daten sollen jedoch aus Gründen der Nachvollziehbarkeit trotzdem importiert werden.
