### ISSUE TITLE
Standort Freigeben Button

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [GeoWerkstatt/ews-boda#68]
Der Button "Standort Freigeben" in der Standortmaske hat noch keine Funktionalität. Erwartungsgemäss soll beim Betätigen des Buttons das Property FreigabeAfu des Standorts auf true gesetzt werden.

**Comment by flenny** [comment]
**markus.staehli (Guest) am Fr. 8. Juli 2022 08:21 Uhr im Teams**
> Externe Büros dürfen Standorte löschen, solange sie noch nicht durch das AfU freigegeben wurden. Freigegebene Standorte hingegen dürfen sie nicht mehr löschen.

**Comment by danjov** [comment]
Das Freigeben von Standorten funktioniert nicht und im UI existieren scheinbar zwei Möglichkeiten einen Standort freizugeben: Einmal über eine Checkbox und einmal über den Button _Standort freigeben_.

* Die Freigabe soll über den Button _Standort freigeben_ erfolgen und nicht über eine Checkbox.

**Comment by StefanKiener** [comment]
Das UI enthält keinen Button _Standort freigeben_, aber immer noch eine (editierbare) CheckBox _Freigabe AfU_

**Comment by danjov** [comment]
@StefanKiener Die Checkbox wurde drin gelassen und der Button gelöscht, da man mit einer Checkbox die Freigabe wieder entfernen kann.
