### ISSUE TITLE
Datenbereinigung für Feld [standort.gemeinde]

### ISSUE THREAD

**Issue by danjov** [GeoWerkstatt/ews-boda#73]
Das Feld `[standort.gemeinde]` lässt sich wie befürchtet nicht aus den bisherigen Daten `[standort.gembfs]` herleiten und muss deshalb für alle Daten mittels Data Service API neu befüllt werden.

**Comment by danjov** [comment]
Die automatische Migration per Data Service API kann nicht alle Daten vollständig bereinigen. Nach der automatisierten Migration auf Prod müssen die verbliebenen Gemeinden manuell bereinigt werden.

**Comment by StefanKiener** [comment]
@danjov Bitte Liste erstellen mit Standorten, die von Hand bereinigt werden müssen.

**Comment by danjov** [comment]
Die automatische Migration auf Prod konnte alle Daten vollständig migrieren und es ist keine manuelle Bereinigung mehr nötig.
